stages:
  - install
  - eslint
  - notify

cache:
  key: '$CI_COMMIT_REF_SLUG'

install:
  stage: install
  cache:
         paths:
           - node_modules/
  script: 
   - cnpm install
  tags:
   - sonar

eslint:
  stage: eslint
  cache:
    paths:
      - node_modules/
  script:
    - npm run lint
  tags:
    - sonar
 
notify-fail:
  stage: notify
  cache:
    paths:
      - node_modules/